version: '3.4'
services:
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/client
  
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    command: npm run server
    ports:
      - 5000:5000
    volumes:
      - ./backend:/server