export const GET_EARTHQUAKES = "GET_EARTHQUAKES";
export const POST_LOCATION = "POST_LOCATION";
export const EARTHQUAKES_LOADING = "EARTHQUAKES_LOADING";
export const LOCATIONS_LOADING = "LOCATIONS_LOADING";